FROM python:3.11-slim AS builder


WORKDIR /app


RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY api/requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt



FROM python:3.11-slim AS runtime


WORKDIR /app


RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq5 \
    && rm -rf /var/lib/apt/lists/*


COPY --from=builder /root/.local /home/appuser/.local


COPY api/app.py ./api/app.py
COPY openapi.yaml ./openapi.yaml

ENV PATH=/home/appuser/.local/bin:$PATH


RUN useradd -u 1000 appuser && chown -R appuser:appuser /app
USER 1000


EXPOSE 5000


CMD ["python", "api/app.py"]
